spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_demo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: {{}}
    password: {{}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
  
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 添加日志配置
logging:
  charset:
      console: UTF-8
      file: UTF-8
  level:
    root: INFO
    org.example.ai_langchain4j_demo: DEBUG
  file:
    path: logs
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
    banner: false


langchain4j:
  siliconflow:
    base-url: https://api.siliconflow.com/v1
    api-key: {}
    model: Qwen/Qwen2.5-7B-Instruct
    strime: true
  embedding-model:
    provider: ollama
    ollama:
      base-url: http://10.2.37.243:11434/
      model: nomic-embed-text:latest
      timeout: 30s

  # embedding-model:
  #   provider: openai
  #   openai:
  #     api-key: your-api-key-here
  #     model: text-embedding-ada-002
  #     timeout: 30s

# 在配置文件中添加
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true



